import Footer from '@/Components/Layout/Footer';
import Header from '@/Components/Layout/Header';

import './globals.css';

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>
        <main className='mx-auto max-w-6xl p-4'>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
